version: "3.7"

services:
    qodana:
        image: jetbrains/qodana-jvm:2021.3-eap
        volumes:
            - ./:/data/project/
        ports:
            - 8080:8080
        command: --show-report
