version: '3.7'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    network_mode: "host"
    volumes:
      - ./data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql