spring:
  datasource:
    url: jdbc:mysql://192.168.0.105:3306/sfg_dev?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: sfg_prod_user
    password: mysql
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false